### ISSUE TITLE
Ranksystem

### ISSUE THREAD

**Issue by Provokan** [jastend/Life-Control#2]
Kannst du mir verraten, wo ich das Ranksystem bearbeiten kann bzw veränderungen vornehmen kann?

**Comment by jastend** [comment]
Hi,

das wird immer über die Session abgefragt. Beispielsweise frage ich Stufe 2 oder höher wie folgt ab:

```
if ($_SESSION['user_level'] >= 2) {
User Level 2 or higher
} else {
User Level 1 or lower
};
```

Will ich eine ganze Seite sperren, frage ich das übrigens mittlerweile direkt bei der Seiteninitialisierung ab. Ein Beispiel findest du hier: https://github.com/jastend/Life-Control/blob/master/vehicles.php

Die aktuell im Master gespeicherte Version ist übrigens deutlich weiter als die vorherige Release-Version und erfordert ein paar Anpassungen an der SQL Tabelle von Life Control, weil ich hier unter anderem auch Admin-Notizen implementiert habe (Admins können also Notizen für Spieler hinzufügen).

Im Prinzip erfordert die Version aber ein grundsätzliches Verständnis für PHP, weil ich viele Sachen direkt so implementiere, wie sie in der Datenbank von KBS-Altis.de gespeichert werden und dadurch sind nicht alle Dinge auf deinem Server verwendbar. Wenn du Interesse daran hast die aktuellste Version zu nutzen, dann sag mir aber bescheid und ich gebe dir die SQL Queries und helfe dir auch gerne bei Fragen.

Wenn du nicht selbst Hand anlegen möchtest, ist die von Cammygames selbst gepflegte Version aber besser für dich. Davon ab habe ich damit begonnen ein Admin-Panel für KBS-Altis.de komplett von Grund auf neu zu schreiben, da dieses Live Control sehr unsauber geschrieben ist. Ich werde das dann wahrscheinlich auch öffentlich zur Verfügung stellen - in wie weit ich es jedoch allgemein kompatibel mache hängt dann vom Interesse ab.

**Comment by Provokan** [comment]
Erstmal vielen Dank für die schnelle und präzise Antwort,

ich habe mir deine Version mal angeschaut, was mich jetzt noch Interessiert sind deine 100 Neusten Spieler, wenn du mir da SQL befehl geben könntest wäre es top :)

**Comment by Provokan** [comment]
Es gibt dennoch ein Fehler, möchte ich über deine Fraud.php auf die EditPlayer.php kommen, gebt er mir die meldung raus dass die Seite editPlayer.php nicht gefunden wurde.

**Comment by jastend** [comment]
Danke auch für den Minor Fix. Ich habe das eben noch überall behoben.

Wegen Fraud: Das fragt einfach die 100 neuesten uids vom Server ab, weil zumindest KBS-Altis die Spalte #timejoined# nicht richtig ausfüllt. Hier der Query:

```
$sql = "SELECT * FROM `players` ORDER BY `uid` DESC LIMIT 100";
```

BTW: Ich habe gestern dann noch die notwendigen SQL Queries dokumentiert um die für v2 (aktuelles Master) notwendige SQL Struktur zu erhalten.

Für ein Update von der v1 Struktur ist das: https://gist.github.com/jastend/d394869b4243b8f4dfef
Für eine Neuinstallation ist das: https://gist.github.com/jastend/e81ea58ebc04d0f38ea9

Und solltest du manuell die Adminnotes in deine Life Control Version einfügen wollen, findest du hier den Commit mit der Implementierung: https://github.com/jastend/Life-Control/commit/ac6cc2e8bce4c3d3fb9e9ae2d5f2449b0256dd34

Lass mich wissen, falls du sonst was brauchst - und wenn du deine Implementierung teilen möchtest bin ich natürlich immer daran interessiert die ein oder andere Idee zu adaptieren.

**Comment by Provokan** [comment]
Erstmal vielen Danke für den Netten und Schnellen Support,

Ich werde dir alle Implenierungen via Nachricht zukommen lassen so dass du vllt etwas für dich darin finden kannst.

__

Was eventuell richtig nice wäre ist, wenn du in den Admin Notiz anstatt der PlayerID den Namen des Spieler aufzeigen lassen könntest.

Poste mal bitte welches Skillsystem ihr nutzt, damit ich den Error aus der Life-Control wegmachen kann :)

**Comment by jastend** [comment]
There you go: https://github.com/jastend/Life-Control/commit/aa6d929640e88d1c4811aa5244932de1c703a310

Das zeigt jetzt beides an, weil Spieler ja auch gerne mal ihren Namen ändern. Du kannst das aber natürlich auch entfernen wenn du magst - wichtig ist ja eher der Query

**Comment by jastend** [comment]
Ok, ich musste gerade noch die Suche anpassen, hatte ich vergessen: https://github.com/jastend/Life-Control/commit/406bfd9fc940f18fd9c67b4ba986c9efe0f4613f

Das Skillsystem ist basierend auf D41 aber stark angepasst. Im Prinzip musst du nur identifizieren wie die Tabelle bei dir heißt und wie die einzelnen Zeilen heißen und dann kannst du es anpassen wie du magst.

**Comment by Provokan** [comment]
Alles klar, das ändern ist ja die einfachste aufgabe. :)
