### ISSUE TITLE
Rcon Passwort für die Server

### ISSUE THREAD

**Issue by Provokan** [jastend/Life-Control#7]
Moin nochmal,

Hast du eine Idee wie ich den Kick button ans laufen kriege ich habe den bereits wieder eingebaut indem ich die <!-- verschoben haben, dennoch fehlt mir die Spalte um das Rcon passwort zu setzen, ich habe es mal in der db.php gesetzt

define( 'SQ_RCON_Pass' , 'password' );

und in der curPlayers.php line 28 folgendes ersetzt 
//$Query->SetRconPassword( $SQ_RCON_Pass );

 $Query->SetRconPassword( SQ_RCON_Pass );

nach der Veränderung, lässt er einfach mal die Spieler liste leer..

**Comment by jastend** [comment]
Ehrlich gesagt nein. Ich wollte mir die Implementierung nochmal im Detail anschauen, aber was da im Moment im Tool ist schaut mir extrem unausgereift aus.

Im Moment glaube ich nicht, dass ich das in nächster Zeit angehen werde.
